site_name: reNgine
site_author: Yogesh Ojha
site_url: https://rengine.wiki
site_description: reNgine is an automated reconnaissance framework meant for information gathering during penetration testing of web applications. reNgine has customizable scan engines, which can be used to scan the websites, endpoints, and gather information.

copyright: "Copyright &copy; 2023 Yogesh Ojha"

repo_url: https://github.com/yogeshojha/rengine
repo_name: reNgine

theme:
  name: material
  custom_dir: docs/overrides
  logo: static/logo.png
  icon:
    repo: fontawesome/brands/github
  favicon: static/favicon.ico
  palette:
    scheme: light
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.instant

nav:
  - Home: index.md
  # - Getting Started: getting-started.md
  # - Usage Guide: usage/index.md
  # - Changelog: changelog.md
  # - Scan Engine Configuration: usage/scan_engine.md
  # - API: api/index.md

markdown_extensions:
  - meta
  - toc:
      permalink: true
  - attr_list
  - admonition
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yogeshojha/rengine
    - icon: fontawesome/brands/discord
      link: https://discord.gg/H6WzebwX3H
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ojhayogesh11

extra_css:
  - assets/style.css

plugins:
  - search
  - badges
