site_name: Cosmos
site_author: Lalit Naphade
site_url: https://www.linkedin.com/in/lalitnaphade/
site_description: Cosmos is an automated reconnaissance framework meant for information gathering during penetration testing of web applications. Cosmos has customizable scan engines, which can be used to scan the websites, endpoints, and gather information.

copyright: "Copyright &copy; 2024 Lalit Naphade"

repo_url: https://github.com/lnaphade/cosmos
repo_name: Cosmos

theme:
  name: material
  custom_dir: docs/overrides
  logo: static/logo.png
  icon:
    repo: fontawesome/brands/github
  favicon: static/favicon.ico
  palette:
    scheme: light
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.instant

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Usage: usage/index.md
  - Scan Engine Configuration: usage/scan_engine.md
  - Changelog: changelog.md
  # - API: api/index.md

markdown_extensions:
  - meta
  - toc:
      permalink: true
  - attr_list
  - admonition
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lnaphade/cosmos
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/lalit_1985

extra_css:
  - assets/style.css

plugins:
  - search
  - badges
